### ISSUE TITLE
include glottolog-cldf

### ISSUE THREAD

**Issue by HedvigS** [cldf-datasets/clld_meta#3]
can glottolog please be included in cldf/contributions.csv :)?

**Comment by johenglisch** [comment]
Hm, the problem is that this data base contains more than just a list of contributions.  It also collections additional information such as [which Glottocodes appear in which data set](https://github.com/cldf-datasets/clld_meta/blob/master/cldf/dataset-languages.csv).

This kind of information is kinda meaningless for glottolog (since by definition it contains literally every glottocode) and would blow up the size of this data set unnecessarily (it would contain literally every glottocode as well).

I could code an exception like ‘add glottolog to contributions but not to anything else’ but that feels weird.  I guess the catalogues live in a different world than the data sets that refer to them, despite both being in cldf.

btw, I wouldn't add the meta data base itself to the data either, for the same reason.

**Comment by xrotwang** [comment]
I agree with @johenglisch . Glottolog just isn't the same kind of dataset as the ones collected here: It is not something you'd need to discover through browsing the catalog. The catalog is rather meant as a device to make these other datasets discoverable - and when for 50% of Glottocodes in the catalog the only dataset about them would be Glottolog, that would seem to be a disservice.

**Comment by HedvigS** [comment]
Okay, right. What I was talking about in https://github.com/SimonGreenhill/rcldf/issues/40 and what I often need is a simple table with just one row per CLDF-dataset with columns for versions, zenodo link etc - including glottolog-cldf - for rcldf for example. I understand that this project here contains more than that, so this isn't a good fit.

what then...hm 🤔

**Comment by xrotwang** [comment]
I think packages like rcldf should probably work with DOIs identifying datasets. In the case of Glottolog this could be the *concept DOI* for Glottolog CLDF, i.e. the DOI that resolves to the latest version. Hard-coding this DOI in a package wouldn't seem to bad/risky.

**Comment by HedvigS** [comment]
> I think packages like rcldf should probably work with DOIs identifying datasets. In the case of Glottolog this could be the _concept DOI_ for Glottolog CLDF, i.e. the DOI that resolves to the latest version. Hard-coding this DOI in a package wouldn't seem to bad/risky.

My understanding of the thread over at rcldf was that @SimonGreenhill doesn't want such a thing in rcldf and that I was directed to use tables overe here in clld_meta instead. But, as this doesn't seem to be a solution in full since it won't include glottolog-cldf, I'm sort of left hanging. I don't know how to convince Simon to include a DOI table in rcldf.

**Comment by xrotwang** [comment]
@HedvigS I think it's reasonable to not include a whole catalog of DOIs of CLDF datasets in rcldf. But again, Glottolog is different. It's arguably a component of the CLDF spec itself in that it provides the catalog of valid Glottocodes. So including a way to retrieve this catalog in rcldf wouldn't seem totally inappropriate. OTOH figuring out this DOI and supplying it to rcldf at runtime doesn't seem too much to ask users, I'd think.
