### ISSUE TITLE
Implement pycldf_dataset_resolver

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/clld_meta#6]
It would be neat, if this dataset also provided code implementing a `pycldf_dataset_resolver` entry point (see https://github.com/cldf/pycldf/blob/9a1adb1443498a9e9576e3159fa728d1cab72965/setup.cfg#L67-L69), maybe making datasets retrievable via dataset locators of the form `github:<org>:<repos>:<version>`?

See https://github.com/cldf/pycldf/issues/181

**Comment by xrotwang** [comment]
They don't need to resolve to a Zenodo DOI, they'd need to resolve to a `pycldf.Dataset` instance, see https://github.com/cldf/cldfzenodo/blob/1a333649c8db5a6b2c27fbe6d66c0864abb1fde8/src/cldfzenodo/api.py#L265-L277
The idea isn't to use this from other python code, but to use it from cldf or cldfbench commands wherever a dataset locator is allowed. So even if this is just one line of code, it would be essential that this line of code "lives somewhere", from where it can be registered as resolver via the entry point.

**Comment by johenglisch** [comment]
>it would be essential that this line of code "lives somewhere"

What I mean is, I don't think this cldfbench is the right ‘somewhere’.  Building a github link does not require any of the data in here, so pulling this whole thing in as a dependency would be kinda weird (especially since this is a cldfbench, which are generally not really supposed to be depended on like a regular python package).

Maybe the code could live a separate *cldfgithub* package (although tiny packages like that always give me bad npm vibes)?  Or it could just live in *pycldf*?

**Comment by xrotwang** [comment]
Ah, yes, you are right. So teaching pycldf to understand a couple of micro-specs like this one for github seems like a good solution.
